In [24]:
import tensorflow as tf
import numpy as np

In [31]:
input1 = tf.constant(np.arange(1,37,1),shape=[1,6,6,1],dtype=tf.float32)
filter1 = tf.constant([[1,-1,-1],[-1,1,-1],[-1,-1,1]],shape=[3,3,1,1],dtype=tf.float32)
strides1 = [1,1,1,1]
padding1 = 'VALID'
print(input1)
print(filter1)


tf.Tensor(
[[[[ 1.]
   [ 2.]
   [ 3.]
   [ 4.]
   [ 5.]
   [ 6.]]

  [[ 7.]
   [ 8.]
   [ 9.]
   [10.]
   [11.]
   [12.]]

  [[13.]
   [14.]
   [15.]
   [16.]
   [17.]
   [18.]]

  [[19.]
   [20.]
   [21.]
   [22.]
   [23.]
   [24.]]

  [[25.]
   [26.]
   [27.]
   [28.]
   [29.]
   [30.]]

  [[31.]
   [32.]
   [33.]
   [34.]
   [35.]
   [36.]]]], shape=(1, 6, 6, 1), dtype=float32)
tf.Tensor(
[[[[ 1.]]

  [[-1.]]

  [[-1.]]]


 [[[-1.]]

  [[ 1.]]

  [[-1.]]]


 [[[-1.]]

  [[-1.]]

  [[ 1.]]]], shape=(3, 3, 1, 1), dtype=float32)


In [32]:
result1 = tf.nn.conv2d(input1, filter1, strides1,padding1)
print(result1.numpy().reshape(4,4))

[[-24. -27. -30. -33.]
 [-42. -45. -48. -51.]
 [-60. -63. -66. -69.]
 [-78. -81. -84. -87.]]


In [33]:
input2 = tf.constant(np.arange(36,0,-1),shape=[1,6,6,1],dtype=tf.float32)
filter2 = tf.constant([[1,-1,-1],[-1,1,-1],[-1,-1,1]],shape=[3,3,1,1],dtype=tf.float32)
strides2 = [1,1,1,1]
padding2 = 'VALID'
print(input2)
print(filter2)

tf.Tensor(
[[[[36.]
   [35.]
   [34.]
   [33.]
   [32.]
   [31.]]

  [[30.]
   [29.]
   [28.]
   [27.]
   [26.]
   [25.]]

  [[24.]
   [23.]
   [22.]
   [21.]
   [20.]
   [19.]]

  [[18.]
   [17.]
   [16.]
   [15.]
   [14.]
   [13.]]

  [[12.]
   [11.]
   [10.]
   [ 9.]
   [ 8.]
   [ 7.]]

  [[ 6.]
   [ 5.]
   [ 4.]
   [ 3.]
   [ 2.]
   [ 1.]]]], shape=(1, 6, 6, 1), dtype=float32)
tf.Tensor(
[[[[ 1.]]

  [[-1.]]

  [[-1.]]]


 [[[-1.]]

  [[ 1.]]

  [[-1.]]]


 [[[-1.]]

  [[-1.]]

  [[ 1.]]]], shape=(3, 3, 1, 1), dtype=float32)


In [42]:
print(input2.numpy().reshape(6, 6))
result2 = tf.nn.max_pool2d(input2,(4,4),  strides2, padding2, data_format="NHWC", name=None)
print(result2.numpy().reshape(3,3))

[[36. 35. 34. 33. 32. 31.]
 [30. 29. 28. 27. 26. 25.]
 [24. 23. 22. 21. 20. 19.]
 [18. 17. 16. 15. 14. 13.]
 [12. 11. 10.  9.  8.  7.]
 [ 6.  5.  4.  3.  2.  1.]]
[[36. 35. 34.]
 [30. 29. 28.]
 [24. 23. 22.]]
